# Generated by Django 2.0.2 on 2018-02-05 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_key', models.CharField(max_length=200, unique=True)),
                ('feature_value', models.CharField(max_length=200)),
            ],
        ),
    ]
